name: White Paper
description: >
    A simple jekyll theme aimed at programmers who like clean interface to write posts
    and show off some code.
about: >
    Página dedicada a la práctica de la materia Análisis de Señales y Sistemas en la Facultad Regional del Neuquén, Universidad Tecnológica Nacional.

master_repo: false
url: "https://1nv1.github.io/UTN-FRN-ASS/"
markdown: kramdown
highlighter: rouge

plugins: ['jekyll-paginate', 'jekyll-gist']

paginate: 3

logo:             logo.png
disqus_shortname:

owner:
  name:           Nelson Lombardo
  avatar:         ""
  email:          "nelson.lombardo@gmail.com"
  # Social networking links used in footer. Update and remove as you like.
  twitter:
  github:
  stackexchange:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:
