# Site settings
title: Análisis de Señales y Sistemas - UTN-FRN
description: "Sitio con recursos para la matería de Análisis de Señales y Sistemas, UTN-FRN"
baseurl: "" # for test: remove string '/space-jekyll-templa' to ''
url: "https://1nv1.github.io/UTN-FRN-ASS/" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.githu.io'
# User settings
username: Nelson Lombardo
user_title: Ing. Electrónico
email: nelson.lombardo@gmail.com
twitter_username: invi_god
github_username:  1nv1
disqus_username: loremipsum

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  - title: inicio
    url: /
  - title: mis posts
    url: /posts
  - title: series
    url: /series
  - title: tags
    url: /tags
  - title: acerca de
    url: /about
# projects in header index
projects:
  - name: ASS-Software
    url: https://github.com/1nv1/ASS-Software
# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
